#!/bin/bash

IMAGE=/isowerfer/isofiles/ubuntuseed.iso
BUILD=/isowerfer/preseediso/

mkisofs -r -V "Ubuntuseed" \
            -cache-inodes \
            -J -l -b isolinux/isolinux.bin \
            -c boot.cat -no-emul-boot \
            -boot-load-size 4 -boot-info-table \
            -o $IMAGE $BUILD
